import { resolve } from "path"

export default function(config, env, helpers) {
  /**
   * Use newer version of @teamsupercell/typings-for-css-modules-loader.
   * A wrapper that automatically generates .d.ts files for loaded CSS.
   * The css-loader > 3 will break the outdated typings-for-css-modules-loader
   * https://github.com/TeamSupercell/typings-for-css-modules-loader
   */
  helpers.getLoadersByName(config, `style-loader`).forEach(({ rule }) => {
    rule.use.push({
      loader: `@teamsupercell/typings-for-css-modules-loader`,
      options: {
        banner: `// Autogenerated by typings-for-css-modules-loader. \n// Please do not change this file!`,
      },
    })
  })

  // Use any `index` file, not just index.js
  config.resolve.alias[`preact-cli-entrypoint`] = resolve(process.cwd(), `src`, `index`)

  // Force webpack to use moment.js directly to avoid cannot find './locale' warnings
  config.resolve.alias.moment$ = resolve(__dirname, `../`, `node_modules/moment/moment.js`)

  if (env.production) {
    config.devtool = false // disable sourcemaps
  }

  return config
}
